apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- spire-namespace.yaml
- agent-account.yaml
- agent-cluster-role.yaml
- agent-configmap.yaml
- agent-daemonset.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-configmap.yaml
- server-service.yaml
- server-statefulset.yaml
- spire-bundle-configmap.yaml
- workload-a-account.yaml
- workload-a-deployment.yaml
- workload-b-account.yaml
- workload-b-deployment.yaml
- broker-account.yaml
- broker-daemonset.yaml