apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-b
  namespace: default
  labels:
    app: workload-b
spec:
  selector:
    matchLabels:
      app: workload-b
  template:
    metadata:
      labels:
        app: workload-b
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: workload-b
      containers:
        - name: client
          image: workload:latest
          imagePullPolicy: Never
          command: ["sleep"]
          args: [ "10000s" ]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
